# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ffdc0041c6fa4772a7375eeceb90ac10ec7e509e5d514e8e1f7739fbeb48d62b5b08f1d819570d42613422d83fabafc0e778f452371cf367da4a53a044702e1

test:
  secret_key_base: 30ff9b0f65613d1c30f6ed68de9f73a9fd7738a2236401de22d08d6db0b1b94056cbf0ca4b54868e22fe3f79f3728c7cd31070816a8e7aecd191435124a8d806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
